baseURL = "/"
languageCode = "zh-CN"
title = "假装斯文"
theme = "ivy"
disqusShortname = "elizen"
hasCJKLanguage = true
enableEmoji = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
  posts = "/post/:year/:month/:day/:slug/"
  newsletter = "/newsletter/:year/:month/:day/:slug/"

[Menus]
  main = [
      {Name = "Posts", URL = "https://elizen.me/posts/"},
      {Name = "NewsLetter", URL = "https://elizen.me/newsletter/"},
      {Name = "Tags", URL = "https://elizen.me/tags/"},
      {Name = "Books", URL = "https://elizen.me/books/"},
      {Name = "Movies", URL = "https://elizen.me/movies/"},
      {Name = "Photos", URL = "https://elizen.me/photos/"}
  ]

[params]
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."
  footer = "&copy; [Elizen](https://elizen.me) 2015 - 2020"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
  highlightjsVersion = "9.12.0"

[params.valine]
  enable = true
    appId = 'HCbjmh0KVI9obm5bTPipB0wQ-gzGzoHsz'
    appKey = 'oq3jypCIFFxab7dpJ6j039jC'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true