baseURL = "https://elizen.github.io/elizen-blog/"
languageCode = "zh-CN"
title = "Elizen's Blog"
theme = "hyde"
disqusShortname = "elizen"
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename/"

[Menus]
  main = [
      {Name = "Archives", URL = "https://elizen.github.io/elizen-blog/post/"},
      {Name = "Elizen‘s Blog", URL = "https://blog.elizen.me"},
      {Name = "Tags", URL = "https://elizen.github.io/elizen-blog/tags/"},
      {Name = "Books", URL = "https://elizen.github.io/elizen-blog/books/"},
      {Name = "Movies", URL = "https://elizen.github.io/elizen-blog/movies/"}
  ]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."
