baseURL = "https://elizen.me/"
languageCode = "zh-CN"
title = "Elizen's Blog"
theme = "ivy"
disqusShortname = "elizen"
hasCJKLanguage = true
enableEmoji = true

[permalinks]
  posts = "/:filename/"

[Menus]
  main = [
      {Name = "Archives", URL = "https://elizen.me/posts/"},
      {Name = "Tags", URL = "https://elizen.me/tags/"},
      {Name = "Books", URL = "https://elizen.me/books/"},
      {Name = "Movies", URL = "https://elizen.me/movies/"},
      {Name = "Photos", URL = "https://elizen.me/photos/"}
  ]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # description abou this website
  description = "There is only one thing in the world worse than being talked about, and that is not being talked about."

[params.valine]
  enable = true
    appId = 'HCbjmh0KVI9obm5bTPipB0wQ-gzGzoHsz'
    appKey = 'oq3jypCIFFxab7dpJ6j039jC'
    placeholder = '既然来了，那就留个痕迹吧~'
    visitor = true